# Generated by Django 5.2.12 on 2026-03-29 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('nip', models.CharField(blank=True, max_length=20)),
                ('regon', models.CharField(blank=True, max_length=20)),
                ('adres', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('strona_www', models.CharField(blank=True, max_length=200)),
                ('status_rejestru', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FakturaSprzedazy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=50)),
                ('data_wystawienia', models.DateField()),
                ('data_sprzedazy', models.DateField()),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kwota_brutto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('czy_oplacona', models.BooleanField(default=False)),
                ('opis', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.kontrahent')),
            ],
        ),
        migrations.CreateModel(
            name='UstawieniaFirmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=200)),
                ('wlasciciel', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=20)),
                ('adres', models.CharField(max_length=300)),
                ('kod_urzedu_skarbowego', models.CharField(blank=True, max_length=10)),
                ('forma_opodatkowania', models.CharField(choices=[('LINIOWY', 'Podatek liniowy')], default='LINIOWY', max_length=20)),
                ('vat_czynny', models.BooleanField(default=False)),
                ('typ_zus', models.CharField(choices=[('PELNY', 'Pełny ZUS'), ('PREFERENCYJNY', 'Preferencyjny ZUS'), ('ULGA', 'Ulga na start')], default='PELNY', max_length=30)),
                ('czy_chorobowe', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDemona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('sciezka_zrodlowa', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('NOWY', 'Nowy'), ('PRZETWARZANY', 'Przetwarzany'), ('OK', 'OK'), ('CZESCIOWO', 'Częściowo'), ('BLAD', 'Błąd')], default='NOWY', max_length=20)),
                ('liczba_rekordow', models.PositiveIntegerField(default=0)),
                ('liczba_bledow', models.PositiveIntegerField(default=0)),
                ('komunikat', models.TextField(blank=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('data_przetworzenia', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='firma_impor_user_id_c2d371_idx'), models.Index(fields=['created_at'], name='firma_impor_created_a38ccf_idx')],
            },
        ),
        migrations.CreateModel(
            name='JPKDeklaracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField()),
                ('miesiac', models.PositiveSmallIntegerField()),
                ('p_17', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_18', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_19', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_20', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_43_korekta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_44_korekta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_45_korekta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_46_korekta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_51', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('p_68', models.BooleanField(default=True)),
                ('p_ordzu', models.BooleanField(default=False)),
                ('uzasadnienie', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rok', '-miesiac', '-id'],
                'unique_together': {('user', 'rok', 'miesiac')},
            },
        ),
        migrations.CreateModel(
            name='FakturaKosztowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_faktury', models.CharField(max_length=100)),
                ('kontrahent_nazwa', models.CharField(max_length=200)),
                ('nip_dostawcy', models.CharField(blank=True, max_length=20)),
                ('kod_kraju', models.CharField(default='PL', max_length=2)),
                ('data_zakupu', models.DateField()),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kwota_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kwota_brutto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategoria', models.CharField(max_length=200)),
                ('rodzaj_zakupu', models.CharField(choices=[('POZ', 'Pozostały zakup'), ('ST', 'Środek trwały')], default='POZ', max_length=10)),
                ('miesiac_jpk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opis', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kontrahent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktury_kosztowe', to='firma.kontrahent')),
            ],
            options={
                'ordering': ['-data_zakupu', '-id'],
                'indexes': [models.Index(fields=['user', 'data_zakupu'], name='firma_faktu_user_id_4f41fd_idx'), models.Index(fields=['user', 'miesiac_jpk'], name='firma_faktu_user_id_c472f2_idx')],
            },
        ),
    ]
