# Generated by Django 5.2.12 on 2026-03-29 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TypOperacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Typ operacji',
                'verbose_name_plural': 'Typy operacji',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='DemonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul', models.CharField(choices=[('DOM', 'Budżet domowy'), ('FIRMA', 'Budżet firmowy')], max_length=10)),
                ('poziom', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Ostrzeżenie'), ('ERROR', 'Błąd')], default='INFO', max_length=10)),
                ('nazwa_pliku', models.CharField(blank=True, max_length=255)),
                ('sciezka', models.CharField(blank=True, max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('wiadomosc', models.TextField()),
                ('utworzono_o', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log demona',
                'verbose_name_plural': 'Logi demona',
                'ordering': ['-utworzono_o', '-id'],
                'indexes': [models.Index(fields=['modul', 'utworzono_o'], name='finanse_dem_modul_c72992_idx'), models.Index(fields=['poziom', 'utworzono_o'], name='finanse_dem_poziom_517577_idx')],
            },
        ),
        migrations.CreateModel(
            name='KontoDomowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=120)),
                ('typ', models.CharField(choices=[('ROR', 'Rachunek bieżący'), ('OSZCZEDNOSCIOWE', 'Konto oszczędnościowe'), ('GOTOWKA', 'Gotówka'), ('FIRMA', 'Konto firmowe')], default='ROR', max_length=20)),
                ('saldo_poczatkowe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aktywne', models.BooleanField(default=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konta_domowe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konto domowe',
                'verbose_name_plural': 'Konta domowe',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='RaportMiesieczny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField()),
                ('miesiac', models.PositiveSmallIntegerField()),
                ('suma_przychodow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('suma_wydatkow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wygenerowano_o', models.DateTimeField(auto_now=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raporty_miesieczne', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raport miesięczny',
                'verbose_name_plural': 'Raporty miesięczne',
                'ordering': ['-rok', '-miesiac'],
            },
        ),
        migrations.CreateModel(
            name='Operacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('data', models.DateField()),
                ('opis', models.TextField(blank=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacje', to='finanse.kategoria')),
                ('konto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacje', to='finanse.kontodomowe')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacje', to=settings.AUTH_USER_MODEL)),
                ('tagi', models.ManyToManyField(blank=True, related_name='operacje', to='finanse.tag')),
                ('typ_operacji', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacje', to='finanse.typoperacji')),
            ],
            options={
                'verbose_name': 'Operacja',
                'verbose_name_plural': 'Operacje',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CelOszczednosciowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.PositiveIntegerField()),
                ('kwota_docelowa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cele_oszczednosciowe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cel oszczędnościowy',
                'verbose_name_plural': 'Cele oszczędnościowe',
                'ordering': ['-rok'],
                'unique_together': {('uzytkownik', 'rok')},
            },
        ),
        migrations.AddConstraint(
            model_name='kontodomowe',
            constraint=models.UniqueConstraint(fields=('uzytkownik', 'nazwa'), name='uniq_konto_user_nazwa'),
        ),
        migrations.AddConstraint(
            model_name='raportmiesieczny',
            constraint=models.UniqueConstraint(fields=('uzytkownik', 'rok', 'miesiac'), name='uniq_raport_user_rok_miesiac'),
        ),
        migrations.AddConstraint(
            model_name='raportmiesieczny',
            constraint=models.CheckConstraint(condition=models.Q(('miesiac__gte', 1), ('miesiac__lte', 12)), name='raport_miesiac_1_12'),
        ),
        migrations.AddIndex(
            model_name='operacja',
            index=models.Index(fields=['uzytkownik', 'data'], name='finanse_ope_uzytkow_4c0a35_idx'),
        ),
        migrations.AddIndex(
            model_name='operacja',
            index=models.Index(fields=['uzytkownik', 'typ_operacji', 'data'], name='finanse_ope_uzytkow_cf74a5_idx'),
        ),
    ]
