-- Oracle bootstrap dla projektu SaldoFlow.
-- Uruchamiaj jako SYS lub SYSTEM.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE PROFILE SF_APP_PROFILE LIMIT
      SESSIONS_PER_USER 10
      FAILED_LOGIN_ATTEMPTS 5
      PASSWORD_LIFE_TIME 90
      PASSWORD_REUSE_TIME 365
      PASSWORD_REUSE_MAX 10
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[CREATE ROLE SF_APP_ADMIN_ROLE]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[CREATE ROLE SF_APP_OPERATOR_ROLE]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[CREATE ROLE SF_APP_AUDITOR_ROLE]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[CREATE ROLE SF_RUNTIME_DAEMON_ROLE]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE ensure_user(p_username VARCHAR2, p_password VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_count FROM DBA_USERS WHERE USERNAME = UPPER(p_username);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY "' || p_password || '" PROFILE SF_APP_PROFILE';
    ELSE
      EXECUTE IMMEDIATE 'ALTER USER ' || p_username || ' IDENTIFIED BY "' || p_password || '"';
      EXECUTE IMMEDIATE 'ALTER USER ' || p_username || ' PROFILE SF_APP_PROFILE';
    END IF;
  END;
BEGIN
  ensure_user('SALDOFLOW_APP', 'ChangeMe_App_2026');
  ensure_user('SALDOFLOW_DAEMON', 'ChangeMe_Daemon_2026');
  ensure_user('SALDOFLOW_AUDIT', 'ChangeMe_Audit_2026');
END;
/

GRANT CREATE SESSION TO SALDOFLOW_APP, SALDOFLOW_DAEMON, SALDOFLOW_AUDIT;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE TO SALDOFLOW_APP;
GRANT CREATE SESSION TO SF_APP_ADMIN_ROLE, SF_APP_OPERATOR_ROLE, SF_APP_AUDITOR_ROLE, SF_RUNTIME_DAEMON_ROLE;

GRANT SF_APP_ADMIN_ROLE TO SALDOFLOW_APP;
GRANT SF_RUNTIME_DAEMON_ROLE TO SALDOFLOW_DAEMON;
GRANT SF_APP_AUDITOR_ROLE TO SALDOFLOW_AUDIT;

COMMENT ON ROLE SF_APP_ADMIN_ROLE IS 'Pełny dostęp administracyjny do aplikacji SaldoFlow.';
COMMENT ON ROLE SF_APP_OPERATOR_ROLE IS 'Rola operatora / księgowego: wprowadzanie i import danych.';
COMMENT ON ROLE SF_APP_AUDITOR_ROLE IS 'Rola audytora: wyłącznie odczyt, raporty i logi.';
COMMENT ON ROLE SF_RUNTIME_DAEMON_ROLE IS 'Rola techniczna dla procesu demona monitorującego importy.';
