-- Kontekst bezpieczeństwa sesji używany przez middleware Django.

CREATE OR REPLACE CONTEXT SF_CTX USING SF_SECURITY_PKG;
/

CREATE OR REPLACE PACKAGE SF_SECURITY_PKG AS
  PROCEDURE SET_CONTEXT(p_user_id IN VARCHAR2, p_role_code IN VARCHAR2);
  PROCEDURE CLEAR_CONTEXT;
END SF_SECURITY_PKG;
/

CREATE OR REPLACE PACKAGE BODY SF_SECURITY_PKG AS
  PROCEDURE SET_CONTEXT(p_user_id IN VARCHAR2, p_role_code IN VARCHAR2) IS
  BEGIN
    DBMS_SESSION.SET_CONTEXT('SF_CTX', 'USER_ID', NVL(p_user_id, '0'));
    DBMS_SESSION.SET_CONTEXT('SF_CTX', 'ROLE_CODE', NVL(p_role_code, 'ANON'));
  END;

  PROCEDURE CLEAR_CONTEXT IS
  BEGIN
    DBMS_SESSION.CLEAR_CONTEXT('SF_CTX', NULL, NULL);
  END;
END SF_SECURITY_PKG;
/
