-- VPD / Row-Level Security dla tabel wielodostępnych.

CREATE OR REPLACE FUNCTION SF_POLICY_OWNER_USER(
  p_schema IN VARCHAR2,
  p_object IN VARCHAR2
) RETURN VARCHAR2 AS
  v_role VARCHAR2(32);
  v_user_id VARCHAR2(64);
BEGIN
  v_role := SYS_CONTEXT('SF_CTX', 'ROLE_CODE');
  v_user_id := SYS_CONTEXT('SF_CTX', 'USER_ID');

  IF v_role IN ('SUPERADMIN', 'ADMIN', 'AUDYTOR') THEN
    RETURN '1=1';
  ELSIF v_user_id IS NULL OR v_user_id = '0' THEN
    RETURN '1=2';
  END IF;

  RETURN 'USER_ID = ' || TO_NUMBER(v_user_id);
END;
/

CREATE OR REPLACE FUNCTION SF_POLICY_OWNER_UZYTKOWNIK(
  p_schema IN VARCHAR2,
  p_object IN VARCHAR2
) RETURN VARCHAR2 AS
  v_role VARCHAR2(32);
  v_user_id VARCHAR2(64);
BEGIN
  v_role := SYS_CONTEXT('SF_CTX', 'ROLE_CODE');
  v_user_id := SYS_CONTEXT('SF_CTX', 'USER_ID');

  IF v_role IN ('SUPERADMIN', 'ADMIN', 'AUDYTOR') THEN
    RETURN '1=1';
  ELSIF v_user_id IS NULL OR v_user_id = '0' THEN
    RETURN '1=2';
  END IF;

  RETURN 'UZYTKOWNIK_ID = ' || TO_NUMBER(v_user_id);
END;
/

CREATE OR REPLACE PROCEDURE SF_ADD_POLICY_IF_EXISTS(
  p_table_name      IN VARCHAR2,
  p_policy_name     IN VARCHAR2,
  p_policy_function IN VARCHAR2
) AS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
  IF v_count = 0 THEN
    RETURN;
  END IF;

  BEGIN
    DBMS_RLS.DROP_POLICY(object_schema => USER, object_name => UPPER(p_table_name), policy_name => UPPER(p_policy_name));
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  DBMS_RLS.ADD_POLICY(
    object_schema    => USER,
    object_name      => UPPER(p_table_name),
    policy_name      => UPPER(p_policy_name),
    function_schema  => USER,
    policy_function  => UPPER(p_policy_function),
    statement_types  => 'SELECT,UPDATE,DELETE'
  );
END;
/

BEGIN
  SF_ADD_POLICY_IF_EXISTS('FIRMA_USTAWIENIAFIRMY', 'SF_VPD_SETTINGS', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FIRMA_KONTRAHENT', 'SF_VPD_CONTRACTOR', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FIRMA_FAKTURASPRZEDAZY', 'SF_VPD_SALES', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FIRMA_FAKTURAKOSZTOWA', 'SF_VPD_COSTS', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FIRMA_JPKDEKLARACJA', 'SF_VPD_JPK', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FIRMA_IMPORTDEMONA', 'SF_VPD_IMPORTS', 'SF_POLICY_OWNER_USER');
  SF_ADD_POLICY_IF_EXISTS('FINANSE_KONTODOMOWE', 'SF_VPD_HOME_ACCOUNTS', 'SF_POLICY_OWNER_UZYTKOWNIK');
  SF_ADD_POLICY_IF_EXISTS('FINANSE_OPERACJA', 'SF_VPD_HOME_OPS', 'SF_POLICY_OWNER_UZYTKOWNIK');
  SF_ADD_POLICY_IF_EXISTS('FINANSE_CELOSZCZEDNOSCIOWY', 'SF_VPD_HOME_GOAL', 'SF_POLICY_OWNER_UZYTKOWNIK');
  SF_ADD_POLICY_IF_EXISTS('FINANSE_RAPORTMIESIECZNY', 'SF_VPD_HOME_REPORT', 'SF_POLICY_OWNER_UZYTKOWNIK');
END;
/
