-- Przykładowe triggery audytowe dla najważniejszych tabel.

CREATE OR REPLACE TRIGGER SF_TRG_AUDIT_FINANSE_OPERACJA
AFTER INSERT OR UPDATE OR DELETE ON FINANSE_OPERACJA
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
BEGIN
  IF INSERTING THEN v_operation := 'INSERT';
  ELSIF UPDATING THEN v_operation := 'UPDATE';
  ELSE v_operation := 'DELETE';
  END IF;

  INSERT INTO SF_DB_CHANGE_LOG(
    ACTOR_DB_USER, APP_USER_ID, ROLE_CODE, TABLE_NAME, ROW_PK, OPERATION, BEFORE_STATE, AFTER_STATE
  ) VALUES (
    USER,
    SYS_CONTEXT('SF_CTX', 'USER_ID'),
    SYS_CONTEXT('SF_CTX', 'ROLE_CODE'),
    'FINANSE_OPERACJA',
    NVL(TO_CHAR(:NEW.ID), TO_CHAR(:OLD.ID)),
    v_operation,
    CASE WHEN DELETING OR UPDATING THEN '{"ID":' || :OLD.ID || ',"UZYTKOWNIK_ID":' || :OLD.UZYTKOWNIK_ID || '}' END,
    CASE WHEN INSERTING OR UPDATING THEN '{"ID":' || :NEW.ID || ',"UZYTKOWNIK_ID":' || :NEW.UZYTKOWNIK_ID || '}' END
  );
END;
/

CREATE OR REPLACE TRIGGER SF_TRG_AUDIT_FIRMA_KOSZT
AFTER INSERT OR UPDATE OR DELETE ON FIRMA_FAKTURAKOSZTOWA
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
BEGIN
  IF INSERTING THEN v_operation := 'INSERT';
  ELSIF UPDATING THEN v_operation := 'UPDATE';
  ELSE v_operation := 'DELETE';
  END IF;

  INSERT INTO SF_DB_CHANGE_LOG(
    ACTOR_DB_USER, APP_USER_ID, ROLE_CODE, TABLE_NAME, ROW_PK, OPERATION, BEFORE_STATE, AFTER_STATE
  ) VALUES (
    USER,
    SYS_CONTEXT('SF_CTX', 'USER_ID'),
    SYS_CONTEXT('SF_CTX', 'ROLE_CODE'),
    'FIRMA_FAKTURAKOSZTOWA',
    NVL(TO_CHAR(:NEW.ID), TO_CHAR(:OLD.ID)),
    v_operation,
    CASE WHEN DELETING OR UPDATING THEN '{"ID":' || :OLD.ID || ',"USER_ID":' || :OLD.USER_ID || '}' END,
    CASE WHEN INSERTING OR UPDATING THEN '{"ID":' || :NEW.ID || ',"USER_ID":' || :NEW.USER_ID || '}' END
  );
END;
/

CREATE OR REPLACE TRIGGER SF_TRG_AUDIT_FIRMA_JPK
AFTER INSERT OR UPDATE OR DELETE ON FIRMA_JPKDEKLARACJA
FOR EACH ROW
DECLARE
  v_operation VARCHAR2(10);
BEGIN
  IF INSERTING THEN v_operation := 'INSERT';
  ELSIF UPDATING THEN v_operation := 'UPDATE';
  ELSE v_operation := 'DELETE';
  END IF;

  INSERT INTO SF_DB_CHANGE_LOG(
    ACTOR_DB_USER, APP_USER_ID, ROLE_CODE, TABLE_NAME, ROW_PK, OPERATION, BEFORE_STATE, AFTER_STATE
  ) VALUES (
    USER,
    SYS_CONTEXT('SF_CTX', 'USER_ID'),
    SYS_CONTEXT('SF_CTX', 'ROLE_CODE'),
    'FIRMA_JPKDEKLARACJA',
    NVL(TO_CHAR(:NEW.ID), TO_CHAR(:OLD.ID)),
    v_operation,
    CASE WHEN DELETING OR UPDATING THEN '{"ID":' || :OLD.ID || ',"USER_ID":' || :OLD.USER_ID || ',"ROK":' || :OLD.ROK || ',"MIESIAC":' || :OLD.MIESIAC || '}' END,
    CASE WHEN INSERTING OR UPDATING THEN '{"ID":' || :NEW.ID || ',"USER_ID":' || :NEW.USER_ID || ',"ROK":' || :NEW.ROK || ',"MIESIAC":' || :NEW.MIESIAC || '}' END
  );
END;
/
