# Generated by Django 5.2.12 on 2026-03-29 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakturaKosztowaArchiwum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archiwum faktur kosztowych',
                'verbose_name_plural': 'Archiwum faktur kosztowych',
                'ordering': ['-deleted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperacjaArchiwum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archiwum operacji',
                'verbose_name_plural': 'Archiwum operacji',
                'ordering': ['-deleted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadministrator'), ('ADMIN', 'Administrator'), ('KSIEGOWY', 'Księgowy'), ('AUDYTOR', 'Audytor'), ('UZYTKOWNIK', 'Użytkownik'), ('DEMON', 'Konto techniczne demona')], default='UZYTKOWNIK', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rola użytkownika',
                'verbose_name_plural': 'Role użytkowników',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Utworzenie'), ('UPDATE', 'Aktualizacja'), ('DELETE', 'Usunięcie'), ('IMPORT_SKIP', 'Pominięcie duplikatu')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log administracyjny',
                'verbose_name_plural': 'Logi administracyjne',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='paneladmin__module_ddc0b9_idx'), models.Index(fields=['entity_type', 'entity_id'], name='paneladmin__entity__a9ba48_idx'), models.Index(fields=['action', 'created_at'], name='paneladmin__action_2113ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignificantDatabaseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='django', max_length=50)),
                ('app_label', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('owner_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant_key', models.CharField(default='system:global', max_length=100)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Istotna zmiana w bazie',
                'verbose_name_plural': 'Istotne zmiany w bazie',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'changed_at'], name='paneladmin__app_lab_6487e7_idx'), models.Index(fields=['owner_user_id', 'changed_at'], name='paneladmin__owner_u_655ca2_idx'), models.Index(fields=['tenant_key', 'changed_at'], name='paneladmin__tenant__996b68_idx'), models.Index(fields=['operation', 'changed_at'], name='paneladmin__operati_b54d95_idx')],
            },
        ),
    ]
