# Generated by Django 5.2.13 on 2026-04-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneladmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__app_lab_132947_idx',
            old_name='paneladmin__app_lab_6487e7_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__owner_u_7efecc_idx',
            old_name='paneladmin__owner_u_655ca2_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__tenant__35add7_idx',
            old_name='paneladmin__tenant__996b68_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__operati_410815_idx',
            old_name='paneladmin__operati_b54d95_idx',
        ),
    ]
