# Generated by Django 5.2.14 on 2026-05-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneladmin', '0002_rename_paneladmin__app_lab_6487e7_idx_paneladmin__app_lab_132947_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__app_lab_6487e7_idx',
            old_name='paneladmin__app_lab_132947_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__owner_u_655ca2_idx',
            old_name='paneladmin__owner_u_7efecc_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__tenant__996b68_idx',
            old_name='paneladmin__tenant__35add7_idx',
        ),
        migrations.RenameIndex(
            model_name='significantdatabasechange',
            new_name='paneladmin__operati_b54d95_idx',
            old_name='paneladmin__operati_410815_idx',
        ),
    ]
